# Generated by Django 4.2.2 on 2024-05-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('imgPath', models.CharField(max_length=300)),
                ('myweigth', models.CharField(max_length=100)),
                ('myheight', models.CharField(max_length=100)),
                ('toDayCalories', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('accountPack', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
    ]
