# Generated by Django 4.2.2 on 2024-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0002_paymentstracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountdetails',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
